#!/usr/bin/env node
/**
 * Regenerate `src/sensors/zone-locations.ts` — every IANA time zone's principal location — from
 * the tz database files of this machine (or of the directory given as the first argument):
 * `zone1970.tab`, `zone.tab` and `tzdata.zi` (for the links, e.g. Asia/Calcutta).
 *
 *     node packages/hud-server/src/tools/generate-zone-locations.ts [/usr/share/zoneinfo]
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { buildZoneTable, parseZiLinks, parseZiVersion, parseZoneTab } from '../sensors/zone-tab.ts';

/** The table module's source for the tz database in `dir`. */
export function renderZoneLocations(dir: string): string {
  const read = (file: string): string => readFileSync(join(dir, file), 'utf8');
  const zi = read('tzdata.zi');
  const { locations, links } = buildZoneTable(
    parseZoneTab(read('zone1970.tab')),
    parseZoneTab(read('zone.tab')),
    parseZiLinks(zi),
  );
  const version = parseZiVersion(zi) ?? 'unknown';
  const sorted = <T>(map: Map<string, T>): Array<[string, T]> =>
    [...map].sort(([a], [b]) => (a < b ? -1 : a > b ? 1 : 0));
  // Quoted only where needed, as the formatter writes object keys.
  const key = (name: string): string => (/^[A-Za-z_$][\w$]*$/.test(name) ? name : `'${name}'`);
  const lines = [
    '// Generated by src/tools/generate-zone-locations.ts from the tz database (public domain):',
    `// zone1970.tab, zone.tab and the links of tzdata.zi, version ${version}. Do not edit by hand.`,
    '',
    "import type { LatLon } from './zone-tab.ts';",
    '',
    '/** The tz database version the table was generated from. */',
    `export const ZONE_TABLE_VERSION = '${version}';`,
    '',
    '/** Principal location of each time zone (latitude, longitude; degrees, 0.01° steps). */',
    'export const ZONE_LOCATIONS: Readonly<Record<string, LatLon>> = {',
    ...sorted(locations).map(([name, [lat, lon]]) => `  ${key(name)}: [${lat}, ${lon}],`),
    '};',
    '',
    '/** Other names of zones (tz database links, e.g. the ones ICU reports), name → zone. */',
    'export const ZONE_LINKS: Readonly<Record<string, string>> = {',
    ...sorted(links).map(([name, target]) => `  ${key(name)}: '${target}',`),
    '};',
    '',
  ];
  return lines.join('\n');
}

const isMain = process.argv[1] !== undefined && fileURLToPath(import.meta.url) === process.argv[1];
if (isMain) {
  const dir = process.argv[2] ?? '/usr/share/zoneinfo';
  const out = fileURLToPath(new URL('../sensors/zone-locations.ts', import.meta.url));
  writeFileSync(out, renderZoneLocations(dir));
  process.stdout.write(`Wrote ${out}\n`);
}
